# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Ebooksforlib"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
    WRAPPER: layouts/main.tt

# Config options for SIP2 auth providers, with examples:
# host: 127.0.0.1:1965
# If the server needs a login before it will talk to clients:
# username: term1
# password: term1
# If the server does not provide the BL and CQ fields to indicate valid 
# usernames and passwords, look for the given string in the AF field:
# auth_denied: 'ikke akseptert'

plugins:
    Auth::Extensible:
        no_default_pages: 1
        realms:
            storevik:
                provider: 'SIP2'
                host: 127.0.0.1:6001
                username: term1
                password: term1
            local:
                provider: 'Database'
                disable_roles: 0
                no_default_pages: 0
