# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Ebooksforlib"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

plugins:
    Auth::Extensible:
        no_default_pages: 1
        no_login_handler: 1
        login_page:  '/in'
        logout_page: '/out'
        exit_page:   '/'
    Lexicon:
        namespace: Ebooksforlib::Lexicon
        func:      [l, _]
        default:   no
        langs:
            en: English
            no: Norsk bokmal
    EscapeHTML:
        automatic_escaping: true
        traverse_objects: true
        exclude_pattern: 'settings'

# template engine
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
    WRAPPER: layouts/main.tt



