=pod

=head1 SQL QUERIES

The admin and superadmin parts of Ebooksforlib are not yet fully built out. 
This file contains some SQL queries that should/could be a part of the UI, 
but that are not yet implemented. Until they are, they can be used from the
command line. 

=head2 Which books are on loan?

A (potentially long) list of all the books that are currently on loan to someone. 

    SELECT 
        f.book_id, 
        b.title, 
        i.file_id, 
        l.* 
    FROM 
        loans AS l, 
        items AS i, 
        files AS f, 
        books as b 
    WHERE 
        l.item_id = i.id AND 
        i.file_id = f.id AND 
        f.book_id = b.id 
    ORDER BY book_id;

=head2 Is a given book on loan to anyone? 

Given a book-ID, this query will show file and item IDs, as well as info 
about who has it on loan. 

    SELECT 
        f.book_id, 
        b.title, 
        f.id AS file_id, 
        i.id AS item_id, 
        l.user_id, 
        l.library_id,
        l.loaned, 
        l.due 
    FROM 
        books as b, 
        files AS f, 
        items AS i 
    LEFT JOIN 
        loans AS l ON i.id = l.item_id 
    WHERE 
        b.id = <book ID> AND 
        b.id = f.book_id AND 
        f.id = i.file_id;

=head2 Which books does a given user have on loan?

Given a user_id, show which books the user has on loan. 

    SELECT
        l.user_id,
        f.book_id,
        b.title,
        l.loaned
    FROM 
        loans as l,
        items as i,
        files as f,
        books as b
    WHERE
        l.item_id = i.id AND
        i.file_id = f.id AND
        f.book_id = b.id AND
        l.user_id = <user_id>;

=head2 How many times has a book been on loan?

=head3 Old and new loans separately

Replace C<old_loans> with C<loans> to see which books are on loan right now.

    SELECT
        b.title,
        b.isbn,
        COUNT(*) as loans
    FROM
        books AS b,
        files AS f,
        items as i,
        old_loans as l
    WHERE
        b.id = f.book_id AND
        f.id = i.file_id AND
        i.id = l.item_id
    GROUP BY
        isbn
    ORDER BY
        loans DESC;

=head3 Old and new loans combined

Ordered by 1. the number of loans, and 2. title.

    SELECT title, isbn, COUNT(*) AS total_loans FROM (
        SELECT
            b.title as title,
            b.isbn as isbn,
            due
        FROM
            books AS b,
            files AS f,
            items as i,
            loans as l
        WHERE
            b.id = f.book_id AND
            f.id = i.file_id AND
            i.id = l.item_id
    UNION ALL
        SELECT
            b.title as title,
            b.isbn as isbn,
            due
        FROM
            books AS b,
            files AS f,
            items as i,
            old_loans as l
        WHERE
            b.id = f.book_id AND
            f.id = i.file_id AND
            i.id = l.item_id
    ) loans
    GROUP BY
        isbn
    ORDER BY
        total_loans DESC,
        title;

=head2 Summary of log for today

This will show the types of actions that have been logged today, and how often 
they have occured, across all libraries.

    SELECT
        logcode,
        COUNT(*) as count
    FROM
        log
    WHERE
        DATE(time) = DATE(NOW())
    GROUP BY
        logcode;

=cut
